name: ci

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache pip
      uses: actions/cache@v3
      with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/dev.txt', 'requirements/prod.txt') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements/dev.txt
    - name: Archive venv
      uses: actions/upload-artifact@v3
      with:
        name: venv
        path: .venv

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download venv
      uses: actions/download-artifact@v3
      with:
        name: venv
    - name: Pytest
      run: python -m pytest tests/

  quality:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download venv
      uses: actions/download-artifact@v3
      with:
        name: venv
    - name: Ruff
      run: python -m ruff check .
    - name: Mypy
      run: python -m mypy .
    - name: Bandit
      run: python -m bandit -r .
