name: ci

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache pip
      uses: actions/cache@v3
      with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/dev.txt', 'requirements/prod.txt') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements/dev.txt
    
    # Testing
    - name: Pytest
      run: python -m pytest tests/
    
      # Quality checks
    - name: Ruff
      run: python -m ruff check .
    - name: Mypy
      run: python -m mypy .
    - name: Bandit
      run: python -m bandit -r -x tests/ .
